services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    # Aquí puedes agregar los otros servicios base

  # Microservicio de Autenticación
  auth-service:
    build: ./services/authentication
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mongodb://auth-db:27017/auth_db
    depends_on:
      - auth-db

  # Base de datos para el servicio de autenticación
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  # --- Plantillas de Microservicios ---
  # TODO: Copiar y modificar "service1" para cada servicio según el tema seleccionado
  
  # Base de datos para el servicio de experiencias
  service1-db:
    image: postgres:latest
    container_name: service1-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=service1_db
    ports:
      - "5432:5432"
    volumes:
      - service1_data:/var/lib/postgresql

  # Microservicio de Experiencias
  experiences-service:
    build: ./services/service1
    container_name: experiences-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mongodb://experiences-db:27017/experiences_db
    depends_on:
      - experiences-db

  # Base de datos para el servicio de experiencias
  experiences-db:
    image: mongo:latest
    container_name: experiences-db
    ports:
      - "27018:27017"
    volumes:
      - experiences_data:/data/db

  # Microservicio de Reservas
  reservations-service:
    build:
      context: ./services/service2
    container_name: reservations-service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://user:password@reservations-db:5432/reservations_db
    depends_on:
      - reservations-db

  # Base de datos para el servicio de reservas
  reservations-db:
    image: postgres:latest
    container_name: reservations-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reservations_db
    ports:
      - "5433:5432"
    volumes:
      - reservations_data:/var/lib/postgresql

  # Microservicio de Evaluaciones
  ratings-service:
    build:
      context: ./services/service3
    container_name: ratings-service
    ports:
      - "8005:8005"
    environment:
      - MONGO_DETAILS=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  auth_data:
  service1_data:
  service2_data:
  service3_data:
  experiences_data:
  reservations_data:
  mongo_data:
